### ISSUE TITLE
YN01 / YN02 / YTRO 200형 전동차

### ISSUE THREAD

**Issue by DAT-TREE** [evepoi/YST#1]
![YN01 무도색](https://user-images.githubusercontent.com/89715231/138585583-10000d15-50ee-4e3a-9395-dd0ad64fc72a.png)
![YN01 warm](https://user-images.githubusercontent.com/89715231/138585596-f846a45b-dd00-4293-91ff-3d97665b8cfb.png)
![YN02](https://user-images.githubusercontent.com/89715231/138585601-5673a5df-889d-4096-a607-c6447e5c42ff.png)
![YTRO 200형](https://user-images.githubusercontent.com/89715231/138585613-2f92868f-a5d0-4c97-8fcb-96bd573e5b0f.png)

**Comment by evepoi** [comment]
확인했습니다.

**Comment by DAT-TREE** [comment]
4차수정
![4차](https://user-images.githubusercontent.com/89715231/138590240-c80a6e06-e7c0-4ab7-b3aa-c4e6c191d316.png)

**Comment by telk5093** [comment]
@DAT-TREE 깃헙에는 …을 눌러 댓글 내용을 수정할 수 있는 기능이 있답니다아

**Comment by evepoi** [comment]
> @DAT-TREE 깃헙에는 …을 눌러 댓글 내용을 수정할 수 있는 기능이 있답니다아

팁정보 감사합니다

**Comment by DAT-TREE** [comment]
아하..
