### ISSUE TITLE
NJ2

### ISSUE THREAD

**Issue by DAT-TREE** [evepoi/YST#10]
![NJ2](https://user-images.githubusercontent.com/89715231/140694895-aabfe116-db80-4da6-8b97-546f312c7eda.png)

중국 칭짱철도에 투입되는 NJ2 디젤기관차입니다.
+ 수정완료

**Comment by evepoi** [comment]
디젤기관차
속도 181km/h
힘 ? 무게? 
도입년도 : 2006 예상중...
