### ISSUE TITLE
SNCF BB15048 가상도색

### ISSUE THREAD

**Issue by DAT-TREE** [evepoi/YST#11]
![SNCF BB15048](https://user-images.githubusercontent.com/89715231/140644285-3e445c58-ff9f-4805-85f8-4d9e7c605cac.png)

프랑스 전기기관차, SNCF BB15048의 가상도색입니다.

**Comment by evepoi** [comment]
전기기관차
속도 181km/h
힘, 무게 ??
도입년도 ??

**Comment by DAT-TREE** [comment]
도입년도는 1971년도로 생각중입니다.
