### ISSUE TITLE
YTRO200 그래픽 깨짐

### ISSUE THREAD

**Issue by DAT-TREE** [evepoi/YST#19]
![1뭐냐](https://user-images.githubusercontent.com/89715231/140979873-0c9b620f-cccf-45f0-9cd9-e76e95531356.png)
![11뭐고](https://user-images.githubusercontent.com/89715231/140979891-88d1ad08-2062-4c62-bbae-9349f77ee0c8.png)

YST 최신 업데이트를 받고나서, YTRO200 빨간열차가 저렇게 깨진 상태가 되었습니다.
타 색상은 문제가 없고 빨간색만 문제가 있네요

**Comment by evepoi** [comment]
다음 업데이트 시 체크하겠습니다.
