### ISSUE TITLE
YTRO 2층객차 디자인 리뉴얼

### ISSUE THREAD

**Issue by DAT-TREE** [evepoi/YST#2]
![YTRO 2층](https://user-images.githubusercontent.com/89715231/138586420-6f7e704f-8f4e-434e-90b7-8862dafbbba8.png)

그린샤 차량을 모티브로, 기존의 YTRO 2층객차 디자인을 바꿔보았습니다.

**Comment by evepoi** [comment]
확인했습니다

**Comment by evepoi** [comment]
https://github.com/evepoi/YST.grf/tree/minengallery/Graphic/locomotive/YTRO
적용되었습니다
