### ISSUE TITLE
MTR 열차 2차 추가 / CR600 스프라이트 수정 및 신도색 추가

### ISSUE THREAD

**Issue by DAT-TREE** [evepoi/YST#23]
![MTR 찐파이널](https://user-images.githubusercontent.com/89715231/142051442-79005001-3fd7-4491-8bfe-7615618d8092.png)

0. **MTR CNR 창춘 전동차와 CRRC 창춘 전동차는 다른 전동차입니다!!! 참고하시길 바랍니다...**

0.5. 메트로카멜 교류형 전동차도 마찬가지... 직류형과는 다른 전동차입니다

1. **MTR 현대로템 R형 전동차를 코딩하실떄, 예상 이미지를 한번 면밀히 살펴보신후, 만들어주셨으면 좋겠습니다.**
**이 열차는 객차 종류가 3개입니다. (일반 객차, 팬터그래프 객차, 1등석 객차)
그리고 한쪽에만 1등석이 달려있습니다.**

**그리고 MTR ADTranZ CAF 전동차의 공항선 버전은, 최고속도가 타 전동차보다 높습니다. (200km/h)
YST내에선 251km/h로 분류될 것으로 예상되네요.**

2. CR600의 스프라이트를 조금 수정했습니다. 3,7번 스프라이트가 지나치게 날카로워보여, 좀 부드럽게 깎아봤습니다.

3. CR600BF 도색이 추가되었습니다.

4. 인게임에선 이 CR600 시리즈의 도색을 CR600AF(빨강열차입니다) , CR600BF(금색열차입니다)로 분류하면 될 것 같습니다.

5. 예전에 말씀하셨던 바이모달 화차 관련 얘기인데, 트럭을 실은 모습은 충분히 구현할 수 있겠으나, **공차를 구현하기가 대단히 어려울 것 같습니다.**  OTTD에 언젠가 이러한 객차 운용방식에 대한 업데이트가 이루어지지 않는 이상 말입니다...

![image](https://user-images.githubusercontent.com/89715231/142052232-ae7bf785-0268-4ffb-8f28-01adc8ce5f87.png)

이게 공차 상태를 보니까, 인게임에 이를 구현하려면 객차 1개가 2개가 되어버리는 모습을 표현해야하거든요...
(두개의 차륜이 트럭 샤시와 합쳐지며 하나의 객차로 합체되는 형태임...)

**Comment by evepoi** [comment]
확인했습니다.
