### ISSUE TITLE
YPW 공통객차

### ISSUE THREAD

**Issue by DAT-TREE** [evepoi/YST#24]
![딩호와](https://user-images.githubusercontent.com/89715231/142206873-f3ea1e0a-9bce-429f-868e-ee1ab8befed6.png)

(이름 옆에 있는 로고는 중국국가철로그룹의 로고입니다. 전기/디젤/증기 셋 중 어디에도 속하지 않는 차이므로 한번 찍어봤는데,
아니다 싶으면 안쓰셔도 무방합니다)

빨간 객차의 발전차는 구글에서 실물 확인후에 찍겠습니다... 찾기가 넘 힘드네여 ㅋㅋ

웬만한 도색의 객차는 다 찍은듯하네요...
25G 객차는 왜 침대차가 없냐면, 좌석차와 침대차가 생긴게 매우 유사해서 그렇습니다...

2층객차도 찍어봤는데, 2층객차의 도색은 대체로 저 K열차 도색이었습니다..(구글링...)
25K 객차에 2층객차 도색개조를 넣어보았습니다.

중국 객차는 참 정보를 모으기가 힘듭니다..
관련 정보 잘 아시는 분들의 의견 감사합니다!!

**Comment by evepoi** [comment]
소중한 자료 감사합니다.
이로써 YST에서도 객차차량이 생겼네요.

추가되는 객차는 좌석차/2층객차/침대차/수화물차등 총 4종이며,
도색으로 25G, 25K, 25T를 선택하도록 할 예정입니다. 또한, 적용된 아이콘로고도 적용하겠습니다.

수용인원은 좌석차 : 80 / 2층객차 : 160 / 침대차 : 50 / 수화물차 : 50
사용년도는 기관차 최소사용기간인 1967년임.
최소편성설정 없음.

**Comment by evepoi** [comment]
중국객차이지만, YST 기관차가 견인하는 공통객차로 YPW로 이름이 변경되어 적용됩니다.
YPW 1F 차량, YPW 2F 차량, YPW 침대차량, YPW 수화물차량, YPW, 발전차
수용인원은 좌석차 : 100 / 2층객차 : 200 / 침대차 : 80 / 수화물차 : 200 / 발전처 수송량 0
견인되는 기관차는 GT26CW를 기본으로하며, 1967년
프랑스 전기기관차 BB15048, 중국기관차 NJ2도 견인할 수 있도록 합니다.
최소편성이 없는 자유편성입니다.
