### ISSUE TITLE
대륙 또는 국가별 매개변수

### ISSUE THREAD

**Issue by SerpensNebula** [evepoi/YST#25]
YST 잘 쓰고 있습니다. 다른게 아니고 업데이트가 계속 되니 열차 종류가 매우 많아져서 지금은 조금 번잡한 것 같네요.

이왕 코드 갈아엎으시는 김에 2cc trains 처럼 국가나 대륙별로 On Off 할 수 있게 매개변수를 추가하면 구매창도 정리되고 쓰기도 더 편할 것 같습니다.

**Comment by evepoi** [comment]
좋은 아이디어입니다. 

이번 업데이트로 인해 열차의 종류가 과감히 백업이 진행될 예정입니다.

매개변수관련하여서는 저도 연구를 해봐야합니다. 처음시도하는 방식이라 어떻게 구현할지여부도 확인해야합니다.
