### ISSUE TITLE
TGV기관차의 도색이 변경되지 않음

### ISSUE THREAD

**Issue by JukjeonWani** [evepoi/YST#26]
![001](https://user-images.githubusercontent.com/88026704/143681383-19c6868c-161a-4227-9d73-cebedc671738.jpg)
![002](https://user-images.githubusercontent.com/88026704/143681384-7c219348-5e7a-4e54-b4e4-0703c50932b9.jpg)
![003](https://user-images.githubusercontent.com/88026704/143681386-20ae3dcb-05b5-4fd8-bfdd-53f30ca1332b.jpg)
![004](https://user-images.githubusercontent.com/88026704/143681387-e256e68a-cdbe-4a8f-af70-2229b2d6af14.jpg)
![005](https://user-images.githubusercontent.com/88026704/143681389-da7e0968-9581-44c8-9d2d-7d5be5daa7bd.jpg)
![006](https://user-images.githubusercontent.com/88026704/143681390-7a047456-9883-4b3f-b30c-98c1a307b362.jpg)

**Comment by evepoi** [comment]
혹시 도색변경 떴나요?

**Comment by JukjeonWani** [comment]
객차만 도색이 바뀌고 기관차 누르면 바꿀 수 있는 도색이 안나옵니다

**Comment by evepoi** [comment]
확인결과 TGV Old Pos에서만 도색관련 코드가 없네요 수정하겠습니다

**Comment by evepoi** [comment]
원인 : 
운전차량 수송량 오류입니다.
기존수치 0일 경우, 도색이 적용되지 않습니다.
도색이 있는 차량은 수송량 1을 설정해야하며, 구매목록에서 운전차량임에도 수송량이 1로 표출됩니다.

하지만, 차량구입후에는 수송량이 없으므로, 구매목록의 수송량 1의 오류 문제는 게임 자체의 특성코드이기에 이를 개선되기 전까지는 유지해야함은 어쩔수 없는 상황으로 보여집니다.

업데이트는 [릴리즈 2021.11.27](https://github.com/evepoi/YST.grf/releases/tag/2021.11.27)로 업로드 됩니다.
또한, 온라인컨텐츠에서도 다운받을 수 있습니다.
