### ISSUE TITLE
[건의]YST 동력객차 추가 요청

### ISSUE THREAD

**Issue by JukjeonWani** [evepoi/YST#27]
현재 YST차량들을 쓰다보면 기끔씩 열차 성능이 부족하다 느껴질 때가 있습니다. 복합열차 구성이 안되는 열차를 장대편성으로 운행하거나 YFX의 경우 열차 힘이 부족해서 가속력이 상당히 느린 경우를 자주 접합니다. 그래서 YST에도 동력객차를 추가해서 열차의 힘을 높일 수 있게 하는 방법 또는 동력분산식 열차에 한해 길이에 따라 힘도 같이 늘어나는 방식을 썼으면 좋겠습니다. jgr 멀티서버에서 YST 열차를 사용하여 직결운행을 할 경우 성능의 차이로 복합열차가 안되는 열차를 투입하는 것에 제약이 생겨 불편합니다.

**Comment by evepoi** [comment]
전반적으로 무게를 줄려야 할거 같습니다.
지하철만해도 10편성만해도 400T이라는 묵중한 무게가 나가버리네요. ㅎ;;

예상 수정방향
무게수치
화차/객차 무게 : 40->15T
2층 객차차량 40->30T
지하철 외 운전차량 80->40T
지하철은 80->20T

힘조절
지하철 10,000->2,000kw
일반열차 10,000->4,000kw
고속열차 10,000->8,000kw
YFX와 2층 견인운전열차, 600km/h 급 열차는 변동없음.

**Comment by evepoi** [comment]
릴리즈 공개 : https://github.com/evepoi/YST.grf/releases/tag/2021.11.30
