### ISSUE TITLE
한국철도공사 220000호대 전동차 (ITX-새마을)

### ISSUE THREAD

**Issue by SerpensNebula** [evepoi/YST#29]
![220000호대 전동차 - ITX-새마을 YST](https://user-images.githubusercontent.com/75788864/149533604-f6170c2e-7239-4b4e-bfb4-1c4833ba1df3.png)

>YST에선 주로 녹색을 주색으로 하고 있습니다. 그외 색은 자유롭게 변경해도 나쁘지 않을듯합니다.
우선 녹색으로 (회사색상 제외)로 YST이슈로 업로드해주시면 적용해보도록 하겠습니다.
https://github.com/KoreanGRF/KoreanTrainSet/issues/307#issuecomment-1012034147

전체적으로 수정해야 할 곳(예를 들면 따로 YST에 어울리는 색감 같은) 있으면 알려주세요.

**Comment by evepoi** [comment]
> 전체적으로 수정해야 할 곳(예를 들면 따로 YST에 어울리는 색감 같은) 있으면 알려주세요.

자료 감사합니다

YST에선 메인이 녹색으로 잡았지만. 지금은 크게 의미가 없어지긴했습니다 ㅎㅎ;
YMT 100이나 Glory 600이 5가지 색이 있습니다. 빨강, 녹색, 노랑, 파랑, 흰색으로 있습니다. 이점은 참고하시면 좋을듯합니다.

외 빨강은 한국열차세트 이슈자료실로 올라갔기에 빨강색의 여부의 스프라이트도 같이 넣어주신다면, YST에서 선공개할수도 있습니다.

**Comment by SerpensNebula** [comment]
저야 그래픽 제작자니 빨리 게임에서 볼 수 있다면 좋겠지만, 한열셋 코드제작자(텔크)께도 물어보시는 게 나을 것 같습니다. 똑같은 열차를 선공개 하는 거니까요.

**Comment by evepoi** [comment]
> 저야 그래픽 제작자니 빨리 게임에서 볼 수 있다면 좋겠지만, 한열셋 코드제작자(텔크)께도 물어보시는 게 나을 것 같습니다. 똑같은 열차를 선공개 하는 거니까요.

전반적으로 여쭤본적이 있습니다.
한국열차세트 이슈자료실에 올라온 스프라이트 자료는 한국열차세트에 포함되지 않았기 때문에 권한이 없으므로, 스프라이트 제작자와 협의하라는 답변을 주셨을 뿐입니다.
추가적으로. 한국열차세트는 실제 운영하는 열차가 우선적으로 공개하는 grf라는 점은 변함이 없다고 하셨기 때문에, 한국열차세트에서 공개하는 것보다 빠르게 볼 수 있다면, YST에서 공개하는 방법도 좋을것이라 생각되어집니다.

따라서, 자료를 주신다면 적용할 의사는 충분히 있다고 말씀드리고 싶습니다.

**Comment by SerpensNebula** [comment]
코드제작자분이 허락해주셨다면 하셔도 됩니다.

![220000호대 전동차 - ITX-새마을](https://user-images.githubusercontent.com/75788864/149570600-1722b72b-315f-4ac3-9397-a9bc23070134.png)
이것은 [한열셋 이슈](https://github.com/KoreanGRF/KoreanTrainSet/issues/307) 에 있는 것입니다. 둘 중 하나 골라서 하시거나 아니면 둘 다 하셔도(개조) 됩니다. 

스프라이트 프리셋 조절은 위 이슈의 예상도를 보고 하시면 됩니다. 예상도를 만든 뒤에 수정을 몇 번 했기 때문에, 자세한 디테일이 조금 다릅니다.

**Comment by evepoi** [comment]
스팩 정보
1. 열차이름 : EMU150 (가칭) 향후 이름 변경될 수 있음
2. 도입시기 : 2023
3. 힘 : 4,000kw
4. 무게 : 운전 40T / 객차 15T
5. 운행속도 : 181km/h
6. 최소운행차량 : 4량이상

**Comment by evepoi** [comment]
릴리즈 공개 : https://github.com/evepoi/YST.grf/releases/tag/2022.1.15

**Comment by Gamunbi** [comment]
죄송합니다만, 원래 한열셋에 올렸던 것을 좀 크게 수정하게 됐습니다..;; 어느 한 쪽만 수정하고 YST의 것은 냅두는 것은 아닌 것 같아서, YST의 EMU-180도 수정하게 됐습니다. YST는 한열셋과 스프라이트들의 경향성이 약간 달라서(↔방향 이음새가 한열셋은 1px 떨어져있는데 YST는 붙어있다던지 등), 살짝 다르게 수정하고 업데이트 해드리겠습니다.

**Comment by evepoi** [comment]
굳이 닫지 않아도 됩니다 ㅠ
