### ISSUE TITLE
신칸센 700계 전동차 (N700계 스프라이트로 적용됨)

### ISSUE THREAD

**Issue by DAT-TREE** [evepoi/YST#3]
![700 N700](https://user-images.githubusercontent.com/89715231/138674785-90657262-fa25-4969-ae24-e8e59779c0e1.png)

**Comment by evepoi** [comment]
자료 확인합니다.
기존 N700차량리뉴얼하고 N700차량 도색으로 대만고속철도를 포함하겠습니다.
닥터엘로우는 시운전차량으로써, 기존 CHR380A-Test 차량과 같은 스팩으로 적용하겠습니다.

**Comment by evepoi** [comment]
2021.10.26일 자료로 추가되었습니다. 다만, 기존 자료의 운전차량 4번, 8번라인의 크기가 맞지 않아 임의적으로 추가했습니다.

보안사항 있으시면 보시고 자료 업해주세요^^

**Comment by NuclearBread** [comment]
700계 스프라이트 가져다가 700계 7000번대 도색을 만들어도 될까요?
![5f7a10293a9e95377cb58f5b7b39cc6a1a2f39d072a8c4b321923f8c2714376d128a63fe05bb941ca8a6721a4cda553da766846888da88493a94cac0e7d00c35cb1b80ccbb673ff4554019cee8d304fd427312930218662c94ba76468ec624d166633930323ec577687480d230742136](https://user-images.githubusercontent.com/81287454/138989484-d2d3113b-1482-4c60-91ff-b44c1081cc27.jpeg)

**Comment by DAT-TREE** [comment]
넵

**Comment by evepoi** [comment]
참고로 700계 스프라이트는 아니고 N700계 스프라이트입니다 참고하세요

**Comment by DAT-TREE** [comment]
제가 700계 전동차랑 N700계 전동차를 하나의 카테고리로 묶어 적용하자고 얘기했었습니다..
(분리하는게 맞다고 생각되신다면 N700과 그냥 700을 나누는 것도 괜찮은 선택이긴 하지만)
그리고 이번에 찍은 스프라이트가 전부 700계 전동차라서 제목을 저렇게 한 것입니다.
레일스타 스프라이트는 아직 없지만, 이것도 700계 전동차입니다.
