### ISSUE TITLE
2층 열차 재도입

### ISSUE THREAD

**Issue by evepoi** [evepoi/YST#30]
한국철도열차중 누리로, ITX-새마을, KTX-산천의 열차를 전량 2층차량으로 도입하고자 합니다.
오래전 이미 도입한적이 있었다가 사라졌습니다.

그 필요성이 있어지면서 추가하고자 합니다.

기존 버전의 그래픽보다 달라질수도 있습니다.

**Comment by JukjeonWani** [comment]
한국형 기관차(GT26CW)가 있는데 한국형 객차가 없으면 약간 모순되지 않을까 하는 생각이 있어서요 2층 무궁화호 객차도 다시 추가했으면 합니다

**Comment by evepoi** [comment]
> 한국형 기관차(GT26CW)가 있는데 한국형 객차가 없으면 약간 모순되지 않을까 하는 생각이 있어서요 2층 무궁화호 객차도 다시 추가했으면 합니다

네 다음 업데이트시 추가하겠습니다.
사실 무궁화2층을 대처하는 열차가 YPW객차였지요
