### ISSUE TITLE
[수정] 한국철도공사 220000호대 전동차 (EMU-180, ITX-새마을)

### ISSUE THREAD

**Issue by SerpensNebula** [evepoi/YST#33]
![전동차 220000호대 - ITX-새마을 YST 2차 완성 - 빨강](https://user-images.githubusercontent.com/75788864/151968738-d2175867-9230-4d50-8a08-44c6f4522325.png)
![전동차 220000호대 - ITX-새마을 YST 2차 완성 - 녹색](https://user-images.githubusercontent.com/75788864/151968749-8a7b23c8-7d4c-457d-9b78-8bf139c40d1f.png)

죄송합니다만, 원래 한열셋 이슈에 올렸던 스프라이트를 좀 많이 수정하게 됐습니다..;; 어느 한 쪽만 수정하고 다른 쪽은 냅두는 것은 아닌 것 같아서, YST의 EMU-180도 수정하게 됐습니다. 

YST는 한열셋과 스프라이트 규격이 미묘하게 달라서(예를 들면 ↔방향 차량들이 한열셋은 1px씩 떨어져있는데 YST는 붙어있음), 한열셋과는 아주 살짝 다르게 수정하고 업데이트 했습니다.

**Comment by evepoi** [comment]
수정 감사합니다. 참고로 YST에는 기본 열차틀이 정해 놓고 작업하고 있습니다. 이에 따라, 해당 프리셋에 맞추어 한두줄 변경하여 적용되었긴 했습니다.

어느 부분이 수정되었는지 궁금합니다.

**Comment by evepoi** [comment]
https://github.com/evepoi/YST/tree/minengallery/src/locomotive/EMU/EMU180
이곳에 이미 공개된 자료가 있습니다.
번거로우시더라도, 수정된 사항을 수정해주셔서 재업로드 부탁드립니다.

지금 있는 빨강, 녹색외 다른 색상(회사색상과는 별도)로 있으면 좋을거 같다는 생각이 듭니다.

SR의 회사 주문용으로 YST는 흰색 차량이 납품됨을 컨셉으로 진행하고 있긴 합니다. (개인적 생각)

**Comment by SerpensNebula** [comment]
>수정 감사합니다. 참고로 YST에는 기본 열차틀이 정해 놓고 작업하고 있습니다. 이에 따라, 해당 프리셋에 맞추어 한두줄 변경>하여 적용되었긴 했습니다.
>
>어느 부분이 수정되었는지 궁금합니다.

아하.. 그렇군요. 세로와 가로 방향은 크게 바뀐 것은 없고, 주로 대각선 방향들(↗↙↖↘)을 한열셋 규격에 맞춰 수정한 거였습니다.  수정은 취소하겠습니다. YST만의 규격이 따로 있으니 그것을 먼저 존중하겠습니다. 

>지금 있는 빨강, 녹색외 다른 색상(회사색상과는 별도)로 있으면 좋을거 같다는 생각이 듭니다.

이 경우에는 흰색버전도 따로 만들어드릴 수 있습니다. 만들까요?

**Comment by evepoi** [comment]
> 아하.. 그렇군요. 세로와 가로 방향은 크게 바뀐 것은 없고, 주로 대각선 방향들(↗↙↖↘)을 한열셋 규격에 맞춰 수정한 거였습니다. 수정은 취소하겠습니다. YST만의 규격이 따로 있으니 그것을 먼저 존중하겠습니다.

감사합니다. 스프라이트 제공자의 입장에선 까다로울수도 있긴 합니다. 1픽셀차이가 열차의 디자인을 좀더 세밀하게 할 수 있다는 의견도 있었던 터라, 현 템플릿을 유지하고 있습니다.

> 흰색버전도 따로 만들어드릴 수 있습니다. 만들까요?

YST에 추가되는 가상열차중 녹색, 흰색은 기본적인 색상으로 유지하려고 하고 있긴 합니다. 만들어 주시면 제가 더 감사할뿐입니다.
흰색외 다른색상도 있으면 좋습니다. YMT 100, 200의 색상을 참고해보셔도 좋습니다.

YST에선 2층 열차도 있습니다. 이점도 감안하여 적용해보시면 좋을듯합니다^^
