### ISSUE TITLE
[질문&요청] YST 세트 자기부상, 협궤 지원 여부 그리고 위키 요청사항

### ISSUE THREAD

**Issue by CoconutKR** [evepoi/YST#37]
질문사항) YST 세트는 현재 일반궤만 사용하는걸로 알고 있습니다만 자기부상열차 혹은 협궤열차를 새로 제작하여 세트에 추가한다면 자기부상선로 혹은 협궤선로에서 운행할수있게 가능한가요?

요청사항) 현재 위키 기여자 목록에 제 닉네임이 Gyeongliner (경부라이너)라고 표기 되어있는데 Gyeongbuliner (경부라이너)로 수정 요청드립니다~

**Comment by evepoi** [comment]
> 질문사항) YST 세트는 현재 일반궤만 사용하는걸로 알고 있습니다만 자기부상열차 혹은 협궤열차를 새로 제작하여 세트에 추가한다면 자기부상선로 혹은 협궤선로에서 운행할수있게 가능한가요?

충분히 가능합니다. 한국기찻길 세트의 선로 구분을 맞춘다면 가능합니다.
(선로코드 : 협궤선로 KRNR, 자기부상 MGLV)
단지, 얼마나 많은 차량이 추가될지 알수가 없기에 나누어 제작할지는 고민해봐야합니다.

> 요청사항) 현재 위키 기여자 목록에 제 닉네임이 Gyeongliner (경부라이너)라고 표기 되어있는데 Gyeongbuliner (경부라이너)로 수정 요청드립니다~

수정해드렸습니다.
