### ISSUE TITLE
[열차 추가] VHST-600X

### ISSUE THREAD

**Issue by CoconutKR** [evepoi/YST#38]
![VHST-600X](https://user-images.githubusercontent.com/85421764/156908668-d0a686e2-4972-4c5b-931a-9cdab8eaeb8c.png)
기존 YST 세트의 HEMU-430X를 기반으로 만들어보았습니다.

열차명 : VHST-600X
사양 : 설계 최고속도 600km/h
편성대수 : 8량

https://namu.wiki/w/VHST-600X

번외) 오늘 여러가지 열차를 더 제작하여 올릴 예정입니다.  이 이슈에서 계속해서 올리도록 하겠습니다.

제작 : 경부라이너(GBLINER)

========== YST 적용내용 ==========
1. 신규차량여부 : 예
2. 도색시 포함할 열차 : 신규차량으로 적용
3. GRF 적용이름 : VHSH-600X
4. 운행속도 : 600km/h
5. 최소편성수 : 8편성

**Comment by evepoi** [comment]
스토리
VHST-600X는 YST 열차셋이 탄생하게 된 초창기 열차였습니다. 당시 600km/h급의 열차가 어느곳에도 없었기에 YST (당시 영선열차세트)를 알리게 된 중요포인트가 되었습니다.

  하지만, 디자인색상부분에서 명암과 색을 정확히 표시할 수 없었기에 형식적인 열차로 운영했었습니다. 600km/h급 열차라는 특징으로 많은 분들이 이용을 했지만 말이죠 ^^

  디자인을 변경하면서 VHST-600의 열차 디자인과는 완전히 달라졌습니다.

2. 기존 VTX열차와의 결합성
  등록해주신 열차는 이름이 바뀌었지만, YST에선 VTX열차입니다.
  본 열차를 VTX와 개별로 가게될지, VTX열차의 디자인 디테일업할지에 대해선 결정되지 않았습니다.

  보다 좋은 결정을 검토해보고 적용해보겠습니다.

**Comment by gyeongburail** [comment]
![EMU-320 신도색](https://user-images.githubusercontent.com/85421764/156923470-f7f1f57b-a4a6-4b8f-a8b5-f286db53a4e8.png)

기존의 YST의 EMU362를 기반으로 만들었으며 실제 EMU-320의 도색 시안 3개중 하나였습니다.
https://www.yna.co.kr/view/AKR20160908089300063 (여기서 2번)

기존 EMU362의 신규 도색으로 추가되는것이 가장 좋을것같다고 생각합니다.
