### ISSUE TITLE
[변경] EMU362 (리뉴얼)

### ISSUE THREAD

**Issue by CoconutKR** [evepoi/YST#41]
- KTS 템플릿 기반 버전
![EMU362_리뉴얼_자체제작](https://user-images.githubusercontent.com/85421764/157073099-1d9bb7c8-0b3a-49ef-9cee-d38b7146e9eb.png)

- YST 템플릿 맞춘 버전
![EMU362_리뉴얼_자체제작_템플릿완료](https://user-images.githubusercontent.com/85421764/157274186-7a5290b0-8822-40ad-a74b-f2c0ba364cec.png)

한국열차세트의 KTX-이음을 기반으로 EMU362를 재작업하였습니다.

========== YST 적용내용 ==========
신규차량여부 : 아니오
적용될 기존 열차 : EMU-362
운행속도 : 362km/h
최소편성수 : 8편성

**Comment by evepoi** [comment]
본이 아니게 회사색상으로 적용함.
