### ISSUE TITLE
[Next update] 다음 업데이트 내용들. (다음 예정 2022.3.26)

### ISSUE THREAD

**Issue by evepoi** [evepoi/YST#46]
수정할 사항, 버그가 발견되면 아래에 작성해주세요.
확인후 적용이 되면, 
https://github.com/evepoi/YST/blob/minengallery/Next_Release.md
에 수정된 사항을 기입해두겠습니다.

수정완료한 사항은 릴리즈 Pre-Releases에 업로드 됩니다.

[수정할 사항들]
- 없음

**Comment by CoconutKR** [comment]
[수정할 사항들+추가]
- 없음.

**Comment by JukjeonWani** [comment]
[수정할 사항들]
- 없음.
