### ISSUE TITLE
[열차추가] SRT 특대형 기관차 (32bpp)

### ISSUE THREAD

**Issue by Pokerface-YUTHMAIN** [evepoi/YST#48]
![GT26CW SRT index 2](https://user-images.githubusercontent.com/101701121/158737956-a214d56c-f29f-4eae-8512-b08b30206328.png)

안녕하세요. 포커페이스입니다.
GT26CW - SRT버전 스프라이트입니다. 

========== YST 적용내용 ==========
신규차량여부 : 예
GRF 도색이름 : SRT 특대형 기관차
운행속도 : 151km/h (일반열차 매개변수 적용)
최소편성수 : 디젤기관차
열차 실존여부 : 가상

**Comment by JukjeonWani** [comment]
열차 실존여부: 실제→가상
기관차는 존재하나 도색은 실존하지 않음

**Comment by evepoi** [comment]
> 열차 실존여부: 실제→가상

가상으로 적용하겠습니다.

**Comment by Pokerface-YUTHMAIN** [comment]
![GT26CW SRT index 2](https://user-images.githubusercontent.com/101701121/158737586-5b64e319-d719-4110-b33b-903fa7ddb7c4.png)
