### ISSUE TITLE
[보류][열차추가] 한국형 레일젯 (KEJET)

### ISSUE THREAD

**Issue by JukjeonWani** [evepoi/YST#53]
======
====[필수스프라이트]==========
![YST_KRJET](https://user-images.githubusercontent.com/88026704/158860538-999f27c7-786f-4f91-96b6-7282e8c9ada2.png)
![YST_RJ1_CH](https://user-images.githubusercontent.com/88026704/159038449-c01e121c-b920-4898-8893-f2aa036ddf09.png)
![YST_RJ2_CH](https://user-images.githubusercontent.com/88026704/159038702-322f0146-2e30-4785-a2bf-65e13fabf302.png)

==========[32bpp스프라이트]==========
주의점. 기본스프라이트가 없으면 본 32bpp는 적용되지 않는것이 기본입니다.
신규차량시 꼭 기본 스프라이트를 우선적으로 작업해주세요.

==========[설명]==========
객차 스프라이트(적용 X)
객차 전방, 기관차 후방
객차 후방, 기관차 전방

==========[YST적용내용]==========
GRF내 열차 이름 : 2층 무궁화 후미객차
이하 2층 무궁화 객차와 동일
열차속도 :
도입년도 : 
객차당 수송량 : 
최소 편성수 : 
실존여부 :

**Comment by evepoi** [comment]
테스트 결과 불가능한 차량으로 확인됨!!
