### ISSUE TITLE
[버그] 구매창 속도표기 오류

### ISSUE THREAD

**Issue by JukjeonWani** [evepoi/YST#65]
==========[버그내용]==========
준고속, 지하철 차량 제외 대부분의 열차의 구매정보에 최고속도가 0km.h로 표시됨
![image](https://user-images.githubusercontent.com/88026704/159199557-1fed548a-b1ca-4a61-8232-738ef3b1a850.png)
![image](https://user-images.githubusercontent.com/88026704/159199519-4bf4015e-a8fd-4787-b6c6-238bc0be1e43.png)
![image](https://user-images.githubusercontent.com/88026704/159199542-ecd724d3-f9f6-498b-a4ce-9f86f8cec6f5.png)
![image](https://user-images.githubusercontent.com/88026704/159199576-455a68ce-3ace-4c14-b258-706c1a06ae51.png)

==========[개선사항]==========
매개변수가 적용되는 차량 중 준고속열차를 제외한 매개변수 기본값을 0이 아닌 이하의 속도로 설정
(일반열차: 150, 고속열차: 331, 고속열차(430km/h 열차): 430)

==========[YST내용]==========
YST 열차 이름 : AGV, AGV COOL, BB15000, CRH 3, CRH380A, CRH380D, CRH430A, CRH430D, CR400, 유로스타 E300, 유로스타 E320, EMU-150, EMU-320, GT26CW, HEMU-430X, HSR-350, HYEL-100, HYEL-200, ICE-SP, ICE 3, ITX-초월, ITX-SM2, KTX-N, KTX-SC2, NJ2 등 일반열차 ~ 430km/h 고속열차에 해당하는 모든 열차
도색 이름 : (미도색시 무시)

**Comment by evepoi** [comment]
해당부분은 매개변수값이 적용된 열차입니다.
즉 매개변수값이 0이 되는 게임상 버그가 발생할 수 있습니다.
매개변수값 초기화 살포시 눌러주시면 정상속도가 나옵니다.
