### ISSUE TITLE
[버그] 비전철화 선로에 2층 공통객차가 나오지 않음

### ISSUE THREAD

**Issue by JukjeonWani** [evepoi/YST#66]
==========[버그내용]==========
![image](https://user-images.githubusercontent.com/88026704/159200272-4c4ea033-131e-4160-83cf-6c00d18864d3.png)
좌: 비전철화, 우: 전철화 선로 차량기지

==========[개선사항]==========
2층 공통객차가 비전철화 선로의 차량기지에 나오도록 수정하여 HYEL-200의 편성을 가능하도록 수정

==========[YST내용]==========
YST 열차 이름 : 2층 공통객차
도색 이름 : (미도색시 무시)

**Comment by evepoi** [comment]
해당부분 수정했습니다. 릴리즈에서 프리 릴리즈에 업로드해두었습니다.
