### ISSUE TITLE
열차 무게에 대하여...

### ISSUE THREAD

**Issue by DAT-TREE** [evepoi/YST#7]
게임이라서 어느정도는 허용될 수 있는 부분이긴 하지만서도, 열차의 무게가 지나치게 가벼운 것 같습니다.
시속 70km까지 가속하는데 1초도 걸리지 않지요. 
이는 곧 롯데월드의 아트란티스가 급발진하는것보다 YST의 10량 열차가 출발하는게 더 빠르다는 것인데..
아무리 게임이라 하더라도 너무 열차가 날라다니는 것 같습니다.  웨이포인트나 신호기 조건문을 통해서 속도에 제약을 걸어보는 시도도 해봤지만, 그래도 그 구간을 벗어나자마자, 70으로 달리던 열차가 순식간에 150을 찍는건 너무 괴리감이 느껴지네요.

그래서 다음 패치에서 지금보다 열차 1량당 무게를 전부 2배 또는 3배로 늘려야한다고 생각합니다. 
                                        (10량 기준 248톤이던 열차가 496톤 또는 744톤으로 바뀌게 될 것입니다.)
완전히 현실적인 가속력을 구현하는건 불가능하더라도, 제로백 1초는 너무 괴리감이 심한 것 같습니다...
다른 분들은 어떻게 생각하시는지요??

**Comment by evepoi** [comment]
개인적으로도 빠르다는 생각도 있긴합니다 ㅎ;;
