### ISSUE TITLE
VLCC 스프라이트

### ISSUE THREAD

**Issue by DAT-TREE** [evepoi/YST#8]
![kvlcc3 git](https://user-images.githubusercontent.com/89715231/139591039-dba5bd87-5353-4097-9412-e502aae2924d.png)

안깨진 원본입니다.

![vlcc 구매 흰](https://user-images.githubusercontent.com/89715231/139591328-606240d9-2f45-4ece-b99c-bf5369c8e64c.png)

배의 크기가 크기인지라, 구매 항목 이미지는 이 이미지를 사용하는 것이 좋아보입니다.

**Comment by evepoi** [comment]
본 관련 자료는 https://github.com/evepoi/YSS.grf 에서 적용되었습니다.
