### ISSUE TITLE
[열차추가] 우체국소포 윙바디 화물차량

### ISSUE THREAD

**Issue by Pokerface-YUTHMAIN** [evepoi/YST#89]
==========[필수스프라이트]==========
기본스프라이트

==========[32bpp스프라이트]==========
![Wing Post T2](https://user-images.githubusercontent.com/101701121/161004067-156c1933-0577-43c0-b32f-b09e3fdeebae.png)

==========[설명]==========
우체국소포 
윙바디 화물 차량 스프라이트입니다.

==========[YST적용내용]==========
GRF내 열차 이름 :
우체국소포 윙바디 화물칸 / Post Wingbody Freight

열차속도 :
도입년도 : 
객차당 수송량 : 
최소 편성수 : 
실존여부 :

**Comment by evepoi** [comment]
[코멘트]
윙바디가 적용된 차량은 YFX의 귀속으로 테스트를 했습니다.
다만, 운전차량에만 귀속되면 활용성이 많이 떨어지므로, 기관차에 연결할 수 있도록 변경하려 합니다.

실제로도 기차에 적용하는 것보다 트럭화물 차량에 적용하는 것이 보다 깔끔하고 시각면으로 더욱 좋아보이는 점이 있기에
좀더 디테일한 방향설정후 코딩진행을 할수 있도록 하겠습니다.
